stages:
  - test
  - quality
  - build
  - deploy
  - stress

cache:
  key: 'cache-detran'
  paths:
  - node_modules/
  
test_job:
  image: registry.es.gov.br/espm/dockers/node:8.12.0-alpine
  stage: test
  script:
     - npm install
     - npm run test
     - npm run test:e2e

quality_job:
  image: registry.es.gov.br/espm/dockers/ci-node_sonar:8.11.2__3.2
  stage: quality
  dependencies:
      - test_job    
  script:
   - npm install
   - npm run test:cov
   - sonar-scanner

build_job:
  stage: build
  image: docker:stable

  services:
    - docker:dind
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY  
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
   
    
deploy_job:
  stage: deploy
  image: registry.es.gov.br/espm/dockers/node:8.12.0-alpine
  only:
    - tags
  script:
    - npm i upgrade-rancher
    - ./node_modules/.bin/upgrade-rancher --IMAGE $CI_REGISTRY_IMAGE:$CI_BUILD_TAG --SERVICE_ID 1s764
  dependencies:
    - build_job

stress_job:
 stage: stress
 image: docker:stable
 dependencies:
   - deploy_job
 only:
   - tags
 services:
   - docker:dind
 script:
   - docker run -i --rm -v $(pwd)/stress:/bzt-configs -v $(pwd)/stress/artifacts:/tmp/artifacts blazemeter/taurus quick_test.yml 2>&1
 artifacts:
  paths:
    - $(pwd)/stress/artifacts
  expire_in: 2 week
